version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Host port mapped to container port

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Replace with your desired admin email
      PGADMIN_DEFAULT_PASSWORD: admin  # Replace with your desired password
    ports:
      - "8054:80"  # Host port 8054 mapped to container port 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  smarkskill:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings

volumes:
  postgres_data:
  pgadmin_data: