version: '3.8'

services:
  db:
    container_name: smartskill_db
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
        - ./postgre/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Host port mapped to container port
    restart: always
    networks:
      - app_network

  pgadmin:
    container_name: smartskill_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Replace with your desired admin email
      PGADMIN_DEFAULT_PASSWORD: admin  # Replace with your desired password
    ports:
      - "8054:80"  # Host port 8054 mapped to container port 80
    volumes:
      - ./postgre/data:/var/lib/pgadmin
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app_network

  smarkskill:
    container_name: smartskill
    build: .
    command: python manage.py runserver 0.0.0.0:8090
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    restart: always
    networks:
      - app_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network: