# core/minio_config.py

from decouple import config

MINIO_STORAGE_ENDPOINT = config("MINIO_STORAGE_ENDPOINT", default="minio:9000", cast=str)
MINIO_STORAGE_ACCESS_KEY = config("MINIO_STORAGE_ACCESS_KEY", cast=str)
MINIO_STORAGE_SECRET_KEY = config("MINIO_STORAGE_SECRET_KEY", cast=str)
MINIO_STORAGE_USE_HTTPS = config("MINIO_STORAGE_USE_HTTPS", cast=bool, default=False)
MINIO_STORAGE_MEDIA_BUCKET_NAME = 'media'
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
MINIO_STORAGE_STATIC_BUCKET_NAME = 'static'
MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True
MINIO_STORAGE_MEDIA_URL = config("MINIO_STORAGE_MEDIA_URL", default="http://localhost:9000/media/", cast=str)
MINIO_STORAGE_STATIC_URL = config("MINIO_STORAGE_STATIC_URL", default="http://localhost:9000/static/", cast=str)
MINIO_STORAGE_MEDIA_USE_PRESIGNED = False
MINIO_STORAGE_STATIC_USE_PRESIGNED = False
